### ISSUE TITLE
Programmatic Execution?

### ISSUE THREAD

**Issue by DanBurkhardt** [Ramotion/navigation-stack#1]
Hey there, 
I don't see this in the doc anywhere, but is there a way to fire this off programmatically?

For example:
1) I have an action for a button, so I display the stack programmatically
2) I can automatically select the index of the destination stack, or simply just the root controller by firing an execution once the reveal animation completes. 

Thanks and this looks like a great library, really great idea and well done. 

Dan

**Comment by 0ber** [comment]
1) use  `public func showControllers()` method for show stack 
2) could you clarify second question?

**Comment by multinerd** [comment]
> I can automatically select the index of the destination stack, or simply just the root controller by firing an execution once the reveal animation completes.

I think what he means is,  can he press a UIButton and have it jump back to, the root view controller, or a specific index.

> user press buttons
> code: present view controllers -> programmatically select index _x_
> user is now at viewController[_x_] (no interaction other than pressing the button)
